# Generated by Django 5.1.7 on 2025-03-18 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_sale_products_alter_saleproduct_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='grand_total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
