# Generated by Django 5.1.7 on 2025-03-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_grand_total_price_alter_saleproduct_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SaleProduct',
        ),
    ]
