# Generated by Django 5.1.7 on 2025-03-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_sale_products_delete_saleproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='products',
            field=models.JSONField(default=list),
        ),
    ]
