# Generated by Django 5.1.7 on 2025-03-18 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_remove_sale_products_sale_product1_sale_product2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='product1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product2',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='quantity2',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='selling_price1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='selling_price2',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_price1',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='total_price2',
        ),
    ]
